/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import conexao.Conexao;
import entidades.Estoque;
import entidades.ProdutoSecundario;
import entidades.TipoProduto;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import util.SalvaHistorico;
import login.*;
/**
 *
 * @author Wilson
 */
public class produtosecundario extends javax.swing.JInternalFrame {

    EntityManager entity = login.entity;
    
    /**
     * Creates new form produtosecundario
     */
    public produtosecundario() {
        initComponents();
        entity.clear();
        entity.getTransaction().begin();
        List<String> lista  = entity.createQuery("SELECT DISTINCT T.descricao FROM TipoProduto T").getResultList();
        entity.getTransaction().commit();
        for(String item : lista){
            tipoproduto.addItem(item.toUpperCase());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        precocompra = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        precovenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tipoproduto = new javax.swing.JComboBox<>();
        codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTextField4.setText("jTextField1");

        setTitle("CADASTRO DE PRODUTOS SECUNDÁRIOS");

        jLabel1.setText("Nome");

        jLabel2.setText("Marca");

        jLabel3.setText("Preço Compra");

        jLabel4.setText("Preço Venda");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo Produto");

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Código do Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marca)
                            .addComponent(precocompra)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tipoproduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precovenda)
                            .addComponent(codigo))))
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precocompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    String nomeproduto = nome.getText();
    String marcaproduto = marca.getText();
    double precocompraproduto = Double.parseDouble(precocompra.getText());
    double precovendaproduto = Double.parseDouble(precovenda.getText());
    String tipo = tipoproduto.getSelectedItem().toString();
    String codigoproduto = codigo.getText();
    
    if(!nomeproduto.equals("") && !marcaproduto.equals("") && !codigoproduto.equals("")
            && precocompraproduto>0 && precovendaproduto>0 && !tipoproduto.equals("")){
        entity.clear();
        entity.getTransaction().begin();
        
        // RECUPERANDO OS TIPOS DE PRODUTOS JA CADASTRADOS
        TipoProduto tp = (TipoProduto) entity.createQuery("SELECT T FROM TipoProduto T WHERE T.descricao='"+tipo+"'").getResultList().get(0);
    
        
        entity.persist(tp);
        
        ProdutoSecundario ps = new ProdutoSecundario();
        ps.setMarca(marcaproduto);
        ps.setNome(nomeproduto);
        ps.setCodigo(codigoproduto);
        ps.setTipo(tp);
        ps.setPreco_compra(precocompraproduto);
        ps.setPreco_venda(precovendaproduto);
        
        entity.persist(ps);
        
        Estoque e = new Estoque();
        e.setDescricao(ps.getNome()+""+ps.getMarca());
        e.setProdutosecundario(ps);
        e.setQuantidade(0);
        entity.persist(e);
        
        entity.getTransaction().commit();
        entity.clear();
        new SalvaHistorico().salvar("O PRODUTO SECUNDÁRIO "+ps.getNome()+", da "+ps.getMarca()+", FOI ADQUIRIDO POR R$"+ps.getPreco_compra()+" E SERÁ COMERCIALIZADO POR R$"+ps.getPreco_venda());
        new SalvaHistorico().salvar("ESTOQUE INICIALMENTE ZERO DO PRODUTO SECUNDÁRIO "+ps.getNome()+" - "+ps.getCodigo());
        JOptionPane.showMessageDialog(null,"PRODUTO CADASTRADO COM SUCESSO!");
    }
}catch(Exception e){
    JOptionPane.showMessageDialog(null,"INFORMAÇÕES INVÁLIDAS");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField precocompra;
    private javax.swing.JTextField precovenda;
    private javax.swing.JComboBox<String> tipoproduto;
    // End of variables declaration//GEN-END:variables
}
